# Generated by Django 6.0 on 2025-12-24 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubAppInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.BigIntegerField(unique=True)),
                ('account_id', models.BigIntegerField()),
                ('installed_date', models.DateField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('user', 'User'), ('org', 'Org')], default='user', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_repo_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('repo_url', models.URLField()),
                ('is_private', models.BooleanField(default=False)),
                ('owner_type', models.CharField(choices=[('user', 'User'), ('org', 'Org')], default='user', max_length=5)),
                ('github_app_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github_app.githubappinstallation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('github_repo_id', 'github_app_installation'), name='unique_repo_per_installation')],
            },
        ),
    ]
