# Generated by Django 6.0 on 2025-12-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
