# Generated by Django 6.0 on 2025-12-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequestevent',
            name='author_avatar_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='pullrequestevent',
            name='author_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
