# Generated by Django 6.0 on 2025-12-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_pullrequestevent_author_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pullrequestevent',
            name='Duplicate_PR_received',
        ),
        migrations.AddConstraint(
            model_name='pullrequestevent',
            constraint=models.UniqueConstraint(fields=('pr_number', 'task', 'action', 'github_delivery_id'), name='Duplicate_PR_received'),
        ),
    ]
