# Generated by Django 6.0 on 2025-12-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_pullrequestevent_duplicate_pr_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequestevent',
            name='title',
            field=models.CharField(default='Will be here', max_length=400),
            preserve_default=False,
        ),
    ]
