# Generated by Django 6.0 on 2025-12-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_pullrequestevent_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pullrequestevent',
            options={'ordering': ['-received_at']},
        ),
    ]
